version: '3.3'
services:
  jenkins:
    build: ./solution/jenkins
    restart: always
    ports:
      - 8080:8080
    networks:
      - poc-telefonica-network
    volumes:
      - jenkins-data:/var/jenkins_home

  nexus3:
    build: ./solution/nexus3
    restart: always
    ports:
      - 8081:8081
    networks:
      - poc-telefonica-network
    volumes:
      - nexus-data:/nexus-data

networks:
  poc-telefonica-network:
    driver: bridge

volumes:
  jenkins-data:
  nexus-data: